-- MySQL Script generated by MySQL Workbench
-- Fri Jun  2 23:37:38 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Lab
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Lab
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Lab` DEFAULT CHARACTER SET utf8 ;
USE `Lab` ;

-- -----------------------------------------------------
-- Table `Lab`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Lab`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL COMMENT 'Ф.И.О пользователя\n',
  `address` VARCHAR(45) NOT NULL COMMENT 'Адрес пользователя',
  `tel_number` VARCHAR(45) NOT NULL COMMENT 'Номер телефона пользователя',
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lab`.`cake`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Lab`.`cake` (
  `cake_id` INT NOT NULL AUTO_INCREMENT,
  `cake_name` VARCHAR(45) NOT NULL COMMENT 'Имя торта',
  `price` DECIMAL NOT NULL COMMENT 'Цена торта (в рублях)',
  `weight` VARCHAR(45) NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cake_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lab`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Lab`.`order` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `cake_id` INT NOT NULL,
  `date` DATE NULL COMMENT 'Дата заказа',
  `status` VARCHAR(45) NOT NULL COMMENT 'Статус заказа',
  PRIMARY KEY (`order_id`),
  INDEX `cake_id_idx` (`cake_id` ASC) VISIBLE,
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `cake_id`
    FOREIGN KEY (`cake_id`)
    REFERENCES `Lab`.`cake` (`cake_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `Lab`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `Lab`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `Lab`;
INSERT INTO `Lab`.`user` (`user_id`, `name`, `address`, `tel_number`) VALUES (DEFAULT, 'Алексей', 'г.Сургут ', '52344324');
INSERT INTO `Lab`.`user` (`user_id`, `name`, `address`, `tel_number`) VALUES (DEFAULT, 'Михаил', 'г. Краснодар', '23444322');
INSERT INTO `Lab`.`user` (`user_id`, `name`, `address`, `tel_number`) VALUES (DEFAULT, 'Андрей', 'г. Екатеринбург', '44322145');
INSERT INTO `Lab`.`user` (`user_id`, `name`, `address`, `tel_number`) VALUES (DEFAULT, 'Екатерина', 'г. Москва', '54363424');
INSERT INTO `Lab`.`user` (`user_id`, `name`, `address`, `tel_number`) VALUES (DEFAULT, 'Анастасия', 'г. Тюмень', '42567968');

COMMIT;


-- -----------------------------------------------------
-- Data for table `Lab`.`cake`
-- -----------------------------------------------------
START TRANSACTION;
USE `Lab`;
INSERT INTO `Lab`.`cake` (`cake_id`, `cake_name`, `price`, `weight`, `category`) VALUES (1, 'торт \"Прага\"', 1195, '900', 'Большой');
INSERT INTO `Lab`.`cake` (`cake_id`, `cake_name`, `price`, `weight`, `category`) VALUES (2, 'Малиновый торт', 1345, '900', 'Большой');
INSERT INTO `Lab`.`cake` (`cake_id`, `cake_name`, `price`, `weight`, `category`) VALUES (3, 'торт \"Сливочная Птичка\"', 790, '600', 'Средний');
INSERT INTO `Lab`.`cake` (`cake_id`, `cake_name`, `price`, `weight`, `category`) VALUES (4, 'торт \"Красный бархат\"', 755, '450', 'Маленький');
INSERT INTO `Lab`.`cake` (`cake_id`, `cake_name`, `price`, `weight`, `category`) VALUES (5, 'торт \"Ореховый по королевски\"', 835, '400', 'Маленький');

COMMIT;


-- -----------------------------------------------------
-- Data for table `Lab`.`order`
-- -----------------------------------------------------
START TRANSACTION;
USE `Lab`;
INSERT INTO `Lab`.`order` (`order_id`, `user_id`, `cake_id`, `date`, `status`) VALUES (1, 1, 5, '08.03.2023', 'Готово');
INSERT INTO `Lab`.`order` (`order_id`, `user_id`, `cake_id`, `date`, `status`) VALUES (2, 2, 4, '14.05.2023', 'Отправлено');
INSERT INTO `Lab`.`order` (`order_id`, `user_id`, `cake_id`, `date`, `status`) VALUES (3, 3, 3, '05.04.2023', 'Изготовление');
INSERT INTO `Lab`.`order` (`order_id`, `user_id`, `cake_id`, `date`, `status`) VALUES (4, 4, 2, '13.05.2023', 'Отправлено');
INSERT INTO `Lab`.`order` (`order_id`, `user_id`, `cake_id`, `date`, `status`) VALUES (5, 5, 1, '15.04.2023', 'Готово');

COMMIT;

