-- MySQL Script generated by MySQL Workbench
-- Fri Jun  2 13:35:06 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Lab
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Lab
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Lab` DEFAULT CHARACTER SET utf8 ;
USE `Lab` ;

-- -----------------------------------------------------
-- Table `Lab`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Lab`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL COMMENT 'Ф.И.О пользователя\n',
  `address` VARCHAR(45) NOT NULL COMMENT 'Адрес пользователя',
  `tel_number` VARCHAR(45) NOT NULL COMMENT 'Номер телефона пользователя',
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lab`.`cake`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Lab`.`cake` (
  `cake_id` INT NOT NULL AUTO_INCREMENT,
  `cake_name` VARCHAR(45) NOT NULL COMMENT 'Имя торта',
  `price` DECIMAL NOT NULL COMMENT 'Цена торта (в рублях)',
  `weight` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cake_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Lab`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Lab`.`order` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `cake_id` INT NOT NULL,
  `date` DATE NULL COMMENT 'Дата заказа',
  `status` VARCHAR(45) NOT NULL COMMENT 'Статус заказа',
  PRIMARY KEY (`order_id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `cake_id_idx` (`cake_id` ASC) VISIBLE,
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `Lab`.`user` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `cake_id`
    FOREIGN KEY (`cake_id`)
    REFERENCES `Lab`.`cake` (`cake_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
